### ISSUE TITLE
Custom datasets

### ISSUE THREAD

**Issue by martinlarsalbert** [quantumblacklabs/kedro#1082]
## Description
I followed the description to create a custom dataset [here](https://kedro.readthedocs.io/en/stable/07_extend_kedro/03_custom_datasets.html#the-complete-example)
This one does not seem to be up to date.

## Context
So that others avoids this problem by following the above example.

## Possible Implementation
I needed to run the __init__ of the inherrited class AbstractVersionedDataSet to get this working:
```
def __init__(self, filepath: str, version: Version = None):
        """Creates a new instance of SimulationDataSet to load / save simulation results (hff5-files) from Seaman at the given filepath.

        Args:
            filepath: The location of the simulation file to load / save data.
        """

        super().__init__(
            filepath=PurePosixPath(filepath),
            version=version,
        )
```

## Possible Alternatives
I or someone else could perhaps update the example similar to the suggestion above?

**Comment by AntonyMilneQB** [comment]
I think this may already be fixed in #979. If you follow the instructions in the [latest documentation](https://kedro.readthedocs.io/en/latest/07_extend_kedro/03_custom_datasets.html) (rather than the stable you were looking at), does it work ok? Latest documentation points to our master branch; stable documentation points to the latest release (currently 0.17.5).

**Comment by martinlarsalbert** [comment]
@MerelTheisenQB was those commits really related to this issue? Or am I misunderstanding things here?

**Comment by martinlarsalbert** [comment]
@AntonyMilneQB I cannot see that there is anything different in the latest documentation [the-complete-example](https://kedro.readthedocs.io/en/latest/07_extend_kedro/03_custom_datasets.html#the-complete-example).

As far as I understand you need to run the super init method to get it working.

**Comment by AntonyMilneQB** [comment]
@martinlarsalbert the difference is that in the latest documentation the dataset inherits from `AbstractDataSet` rather than `AbstractVersionedDataSet`. `AbstractDataSet` doesn't define an `__init__`, so no need to do `super().__init__`.

Don't worry about the commit, it's not related - the notification is just an artefact of the way we sync between different repositories.

**Comment by martinlarsalbert** [comment]
Aha then I guess that it works, if you say so, thanks!
By the way if I want to install "latest" instead of "stable" can I do that from pypi or should I get it from GitHub instead?

**Comment by AntonyMilneQB** [comment]
If you want to install anything other than a release then you will need to do it from Github. The latest (`master` branch) should install using `pip install git+https://github.com/quantumblacklabs/kedro.git`. Only release are published to PyPI (so you can do `pip install kedro==0.17.5` etc.).

You can install other branches etc. too from Github - see https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch.
