### ISSUE TITLE
"kedro run" not included in --help option though it works

### ISSUE THREAD

**Issue by ajit555db** [quantumblacklabs/kedro#119]
```
$ kedro -h
Usage: kedro [OPTIONS] COMMAND [ARGS]...

  Kedro is a CLI for creating and using Kedro projects For more information,
  type ``kedro info``.

  When inside a Kedro project (created with `kedro new`) commands from the
  project's `kedro_cli.py` file will also be available here.

Options:
  -V, --version  Show version and exit
  -v, --verbose  See extensive logging and error stack traces.
  -h, --help     Show this message and exit.

Global commands from Kedro
Commands:
  docs  See the kedro API docs and introductory tutorial.
  info  Get more information about kedro.
  new   Create a new kedro project.
```

* Kedro version used (`pip show kedro` or `kedro -V`):
Name: kedro
Version: 0.15.2
Summary: Kedro helps you build production-ready data and analytics pipelines
Home-page: https://github.com/quantumblacklabs/kedro
Author: QuantumBlack Labs
Author-email: None
License: Apache Software License (Apache 2.0)
Location: /home/ajit/miniconda3/envs/data/lib/python3.7/site-packages
Requires: requests, cookiecutter, click, memory-profiler, toposort, anyconfig, python-json-logger, xlsxwriter, PyYAML, s3fs, pip-tools, pyarrow, pandas, SQLAlchemy, tables, xlrd
Required-by: 

* Python version used (`python -V`):
Python 3.7.3

* Operating system and version:
Ubuntu 18.04

**Comment by lorenabalan** [comment]
Hi @ajit555db, thank you raising this! This is actually expected behaviour. The three commands you see listed there, `docs`, `info` and `new`, work generally anywhere in your filesystem if you have Kedro installed (why we called them  "global"). Commands like `run` or `test` are project-specific, and you can find them in `kedro_cli.py` of your project root. They don't make sense anywhere that's not a Kedro project. If you run `kedro -h` inside a Kedro project, you will see those listed as well, under "project-specific commands".

**Comment by ajit555db** [comment]
Thanks for the explanation. I just started using it yesterday. After reading the documentation, realized the same.

https://kedro.readthedocs.io/en/latest/06_resources/03_commands_reference.html
