### ISSUE TITLE
[KED-1271] Not able to save tensorflow dataset to a variable and access it from the next node

### ISSUE THREAD

**Issue by pryanga-wk** [quantumblacklabs/kedro#123]
## Description
Kedro is used to build a tensorflow image classification problem. As a first step, TensorFlow dataset is created before passing it to a tensorflow model. I am trying the implement the cactus classification example https://towardsdatascience.com/easy-image-classification-with-tensorflow-2-0-f734fee52d13

## Context
kedro.io.core.DataSetError is thrown when tensor datasets are created.

#### My Code Snippet:
```
def create_tf_dataset(train_filenames, val_filenames, train_labels, val_labels, parameters: Dict[str, Any]):
    batch_size = parameters['BATCH_SIZE']
    buffer_size = parameters['BUFFER_SIZE']
    num_train = len(train_filenames)
    train_data = tf.data.Dataset.from_tensor_slices(
        (tf.constant(train_filenames), tf.constant(train_labels))
    )
    val_data = tf.data.Dataset.from_tensor_slices(
        (tf.constant(val_filenames), tf.constant(val_labels))
    )

    train_data = (train_data.map(_parse_fn)
                  .shuffle(buffer_size=buffer_size)
                  .batch(batch_size)
                  )
    val_data = (val_data.map(_parse_fn)
                .shuffle(buffer_size=buffer_size)
                .batch(batch_size)
                )
    return train_data, val_data, num_train
```

## Expected Result
The train_data and val_data to carry the tensorflow datasets and be accessible by the next node in the pipeline.

## Actual Result
```
raise DataSetError(message) from exc
kedro.io.core.DataSetError: Failed while saving data to data set MemoryDataSet().
can't pickle _thread.RLock objects
```
## Your Environment
* Kedro version used (`pip show kedro` or `kedro -V`): 0.15.2
* Python version used (`python -V`): 3.7.4
* Operating system and version: Ubuntu 18.04

**Comment by 921kiyo** [comment]
Hi @pryanga-wk thank you for raising an issue!

Looks similar to the issue in https://github.com/quantumblacklabs/kedro/issues/91#issuecomment-530814142 Could this be a workaround for you?
https://github.com/quantumblacklabs/kedro/issues/91#issuecomment-530814142

**Comment by pryanga-wk** [comment]
Thanks @921kiyo ! As said in teh issue #91 , overriding MemoryDataset is dangerous and my team is not in a position to take the risk. But thank you for pointing this out.

**Comment by yetudada** [comment]
@pryanga-wk Is #176 a possible solution for this error?

**Comment by yetudada** [comment]
This ticket has a tag for our internal tracker. It appears that #176 will solve this issue.

**Comment by andrii-ivaniuk** [comment]
The new dataset was added in 75e7fb6678b6fdc73ad088ade20666016ecd5a85 commit.

**Comment by fjp** [comment]
@yetudada, @andrii-ivaniuk I don't think that #176 is a solution for this issue and it should be reopened. #176 is used to save/load trained tensorflow models. The author of this issue asked about accessing a [tensorflow.data.Dataset](https://www.tensorflow.org/api_docs/python/tf/data/Dataset) in the next node. I guess saving generic `tf.data.Dataset`s will be difficult because [`tf.data.experimental.save`](https://www.tensorflow.org/api_docs/python/tf/data/experimental/save) will not always work. A workaround is to save the `tf.data.Dataset` as [`tfrecords`](https://www.tensorflow.org/tutorials/load_data/tfrecord) but this requires a dictionary mapping the feature name to the tf.Example-compatible data type.

I think the simplest way, without saving the `tf.data.Dataset` (which is not always required), would be to pass the returned `tf.data.Dataset` to the next node and don't use the `MemoryDataset`. However I don't know if kedro can be easily configured to do this.
