### ISSUE TITLE
pipeline only_nodes function does not maintain pipeline name.

### ISSUE THREAD

**Issue by JoostDuisters** [quantumblacklabs/kedro#130]
## Description
If you use the `only_nodes` function in the Pipeline class you lose the `name` value.

## Context
I have named my pipeline. However when I run it with the nodes tag from the CLI the name is not there anymore. This is a direct result of the fact that this function returns a new `Pipeline` object without the name tag:

![image](https://user-images.githubusercontent.com/41304973/66938171-a5ae2900-f038-11e9-98d1-0d59dfb8f1b5.png)

My particular use case is that I have written my own runner class that prints the name of the pipeline to console. When I use the --node tag for instance it will print "Running pipeline None".

**Comment by Flid** [comment]
Pipeline name is a weird thing really, it just tags all nodes, and then it's left on the pipeline object, but doesn't affect anything. We are deprecating it in the next release anyway in favour of a `tags` parameter.

**Comment by tolomea** [comment]
> I have written my own runner class that prints the name of the pipeline to console.

Why do you need the runner to do that? why can't you print it before handing off to the runner?

**Comment by JoostDuisters** [comment]
Hi Gordon, good point, I don't need the runner for this.

However, this is besides the point. I think there are more situations in which a user might adjust the KedroContext and in doing so use the `name` property of the Pipeline class.

For them it would be unexpected behaviour that this property would be `None` whenever they run the pipeline with the `--node` tag or the `--from-nodes` for instance.

**Comment by tolomea** [comment]
As Anton noted the `name` argument and property are going away in favor of a `tags` argument to `Pipeline.__init__` and no property, this is being done because name only ever influenced the node tags, and now the keys in the dictionary returned by _get_pipelines serve as name.

However if we imagine that wasn't happening. I'd like to get into the rational for not preserving name for a moment.
Essentially what it comes down to is we treat each distinct Pipeline as being a new Pipeline regardless of how it was created. Consider the following examples:
```a=Pipeline(..., name="water").to_nodes()```
```b=Pipeline(Pipeline(..., name="ds"), Pipeline(..., name="de"))```
```c=Pipeline(..., name="ds") | Pipeline(..., name="de")```
```d=Pipeline(..., name="ds") & Pipeline(..., name="de")```
I imagine you'd argue that in the first case the water name should be preserved but in the other cases the ds and de names should be dropped.
But then if you go back to `_filter_pipeline`, which applies the `--node` flag you'll see that it combines the various flags like this:
```
        if from_nodes:
            new_pipeline &= pipeline.from_nodes(*from_nodes)
        if to_nodes:
            new_pipeline &= pipeline.to_nodes(*to_nodes)
        if node_names:
            new_pipeline &= pipeline.only_nodes(*node_names)
        if from_inputs:
            new_pipeline &= pipeline.from_inputs(*from_inputs)
```
So now what? `&` drops the names if there are more than one? but if all pipes have the same name we keep the name? This does not seem more intuitive.

**Comment by JoostDuisters** [comment]
Yes you're right this is problematic the way `--node` uses the `&=` operator.

My argument is simple: filter-like operations shouldn't drop the name because it is not intuitive. It should return a "filtered-down" version of the same object, or at least that is what the UX should feel like.

Not hung up on this at all if like you said the name tag is being removed anyway. I'm simply raising that I don't find it intuitive the way the name disappears when you use the `--node` tag (or any of the other filter-like operations).

**Comment by lorenabalan** [comment]
Hi @JoostDuisters , I'll go ahead and close this issue, given the fact that pipeline `name` is deprecated, and there is no other metadata on the pipeline that should be preserved. Thank you for raising this though, we'll keep it in mind if we do ever introduce any other information on the pipeline.
