### ISSUE TITLE
[KED-1124] kedro install fails to update the installed kedro version

### ISSUE THREAD

**Issue by iver56** [quantumblacklabs/kedro#131]
## Description

`kedro install` is unable to change/update/uninstall the currently installed kedro version

## Context

I was trying to get started with a kedro project, and I needed kedro to be able to run `kedro install`, so I ran `pip install kedro` before doing anything else

## Steps to Reproduce

1. `pip install kedro` (this gave me kedro 0.15.3)
2. Clone a git repository with a kedro project, which was intialized with kedro 0.15.1, so that `kedro==0.15.1` was specified in the requirements.txt file
3. Run `kedro install` in the context of that project

## Expected Result
I expected the `kedro install` command to complete without problems.

## Actual Result
I got an error like this:

```
  Found existing installation: kedro 0.15.1
    Uninstalling kedro-0.15.1:
      Successfully uninstalled kedro-0.15.1
ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Ingen tilgang: 'C:\\Users\\Iver\\AppData\\Local\\Temp\\pip-uninstall-4ty9ouew\\kedro.exe'
Consider using the `--user` option or check the permissions.
```

"Ingen tilgang" translates to "Access is denied". I think this occurs because kedro.exe is being used (by `kedro install`) while the pip subprocess is trying to uninstall it (kedro.exe) before replacing it with a different version.

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): See notes above
* Python version used (`python -V`): 3.7.4 (64-bit) installed with `conda`
* Operating system and version: Windows 10

**Comment by 921kiyo** [comment]
Thank you for reporting it! I followed the steps and was able to reinstall kedro 0.15.1 (though in my macbook). Could you `pip uninstall kedro` and run `kedro install` to see if you can get the correct version of Kedro? 
Also the the error you pasted says uninstalling kedro 0.15.1, which means 0.15.1 was already installed? I expected to see `uninstalling kedro 0.15.3` rather than 0.15.1.

**Comment by iver56** [comment]
Ah, yes, there's more to the story :) After the initial error, I re-ran the `kedro install` command after patching requirements.txt. That's why it says in the error that it was trying to uninstall kedro 0.15.1

**Comment by mzjp2** [comment]
> This may be a Windows-specific issue. Windows probably locks any exe file that is currently running.

This is exactly right. People used to run in this problem all the time on Windows when using `pip` to  upgrade `pip`, the workaround for that was to run `pip` as a python module rather than by itself.

One way to circumvent this on `kedro`'s side is, for the `install` command, which eventually calls `subprocess.run` (which calls `subprocess.Popen` under the hood), you could use `subprocess.Popen` directly and pass a `CREATE_NEW_CONSOLE` or `DETACHED_PROCESS` flag  to indicate that `subprocess` should run the command in a detached process, without waiting for it to complete and then immediately quit after, so that `pip` can uninstall `kedro`. Could probably add checks so that this behaviour only happens on Windows too.

That said, I don't know if it's worth it, when the workaround is as simple as running `pip install -r requirements.txt` yourself.

**Comment by iver56** [comment]
In that case, you could implement something like this until a better solution is in place:

```
function kedro install:
    if os is windows and kedro version would be changed by running kedro install:
        print("This command would try to change the installed kedro version. This does not work on Windows at the moment. Please run this command instead: `pip install ...(insert proper command`")
        exit()
    else:
        # perform normal kedro install procedure
```

Another question to ask is: What value does `kedro install` add compared to just running `pip install -r requirements.txt`? A shorter (albeit unfamiliar and potentially confusing to new users) command?

**Comment by iver56** [comment]
Closed by https://github.com/quantumblacklabs/kedro/commit/fbbcd98b6fa3eb251e8a61008f536f1207cf18ef

**Comment by mzjp2** [comment]
Nice one @DmitriiDeriabinQB! 🚀
