### ISSUE TITLE
Can't call columns from tables

### ISSUE THREAD

**Issue by sofiacosta29** [quantumblacklabs/kedro#154]
Hello! I've completed the Kedro tutorial and I found this tool very interesting. So, I tried to apply Kedro with a different Pipeline. However, there is a node function that used to call the columns from a table and now I can't make it happen. It shows an error saying that the parser "got an unexpected keyword argument 'columns'" when I try to call the columns from the data catalog, where those are registered as follows:

table_x:
  type: CSVLocalDataSet
  filepath: data/01_raw/table_x.csv
  load_args: 
    delimiter: ;
    columns: ['a', 'b', 'c', 'd']

Also, it used to show a different error before, saying that column 'a' wasn't in the data catalog.

The function is defined as follows:

def function(df: pd.DataFrame, df_columns: list = []) -> pd.DataFrame:
...

and it is called from the following node in the pipeline:

node(function, ["table_x", "a","b"], "result_x", name='result_y')

Please note that I am new to Python and that I have never used a pipeline before.

Thank you very much for your attention!

**Comment by yetudada** [comment]
Hi @sofiacosta29 💥 Thank you so much for creating this issue. I will try my best to assist you on this. 

The `CSVLocalDataSet` that you're using from the Data Catalog works with the load and save arguments specified in the Pandas API for `read_csv`. I suspect your error is caused by using the incorrect argument to select columns. You may have to use `usecols` for CSV files, as opposed to `columns` for HDF and Parquet files.

You can find more detail about that here: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html 

Please do try this and let me know if it rectifies your problem.

**Comment by sofiacosta29** [comment]
Thank you very much for your response, it worked!

Also, thank you for the explanation, it helped a lot!

**Comment by yetudada** [comment]
Ah! I'm glad you're sorted. 🎉  Is it okay if I use the contents of this question on Stack Overflow? But otherwise I'll close this question.

**Comment by sofiacosta29** [comment]
Yes, for me it is okay. :) However, when I insert a lot of columns in the "usecols" argument, it pops an error saying "while parsing a flow sequence ... did not find ',' or ']' " when I have used them. Do you have any idea on what is going on, please?
