### ISSUE TITLE
[KED-1031] Spark Session Issue

### ISSUE THREAD

**Issue by KirtikumarShinde** [quantumblacklabs/kedro#171]
## Description
The sample pipeline with nodes creates a spark session everytime we run kedro command like kedro viz or kedro docs.

## Context
Unnecessary spark session created whenever we use kedro commands. Ideally spark session should be created only when using 'kedro run''

## Steps to Reproduce
1. Generate sample pipeline
2. run 'kedro build-docs'
3. this would create spark session

## Expected Result
Spark session would be created when we use kedro run. 

## Actual Result
Spark session is created everytime you run any kedro command.

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.15.4
* Python version used (`python -V`): 3.6.9
* Operating system and version: Linux

**Comment by lorenabalan** [comment]
Thanks @KirtikumarShinde for surfacing this! My response is based on the assumption that you followed our documentation for setting up a Spark session. This is happening because `init_spark_session` is called from the `__init__` function in `ProjectContext`, which means anytime `load_context` is run, for example by `kedro viz`, it initialises the Spark session. A better idea might be to call it from `run`.

We're in the process of improving our understanding of the Spark workflow and we'll update the code and [related documentation](https://kedro.readthedocs.io/en/latest/04_user_guide/09_pyspark.html) once we've agreed on best practice.

**Comment by limdauto** [comment]
Hi @KirtikumarShinde, in Kedro 0.16 and above, there is a new feature called [Hooks](https://kedro.readthedocs.io/en/stable/04_user_guide/15_hooks.html) that could help with this issue. You can put the Spark session initialisation inside `before_pipeline_run` hooks and it won't interfere with other plugin commands.

I'm going to be closing this issue but please feel free to open it if you still have questions.
