### ISSUE TITLE
[KED-1268] Support for SSH data stores

### ISSUE THREAD

**Issue by anferico** [quantumblacklabs/kedro#172]
## Description
I think it would be nice to have the possibility to retrieve/store data from/on an SSH server. Right now, the only way to access remote data is through an HTTP server or an S3 bucket (please correct me if I'm wrong).

## Context
If this feature was enabled, I could store my datasets on my own private server, which would be key to ensure data privacy.

**Comment by tolomea** [comment]
We are investigating fsspec support, that would include SSH support.

**Comment by yetudada** [comment]
@anferico A subsequent release of `kedro` will support a new series of file-storage agnostic datasets for `CSVDataSet`, `ParquetDataSet`, `JSONDataSet`, `ExcelDataSet`, `HDFDataSet` and `PickleDataSet` made possible because we stumbled into `fsspec` while we were looking at Dask integration; these datasets will support SSH.

**Comment by yetudada** [comment]
I've also just placed this on our internal tracker to let you know when this release is ready.

**Comment by yetudada** [comment]
@anferico This PR has been addressed and will be ready for the next release. The datasets which retrieve/store data from/on an SSH server are in the `develop` branch: https://github.com/quantumblacklabs/kedro/tree/develop/kedro/extras/datasets

They all use [`fsspec`](https://filesystem-spec.readthedocs.io/en/latest/) to load access SSH servers: https://filesystem-spec.readthedocs.io/en/latest/api.html#built-in-implementations
