### ISSUE TITLE
[KED-1369] Allow user to decide type of copy in CachedDataSet

### ISSUE THREAD

**Issue by MigQ2** [quantumblacklabs/kedro#216]
## Description
I was trying to use a `CachedDataSet` to save/load some pyspark objects (e.g. pyspark MLlib models from a pickle file using a custom DataSet implementation) and I found it failed because it's trying to deepcopy it. I would like to be able to cache this type of datasets and, more broadly, have more control on how datasets are cached.

## Possible Implementation

After investigating a bit deeper I think the problem is on the `save` method of `MemoryDataSet`, which is what is used as a cache:

```python
    def _save(self, data: Any):
        if isinstance(data, (pd.DataFrame, np.ndarray)):
            self._data = data.copy()
        elif type(data).__name__ == "DataFrame":
            self._data = data
        else:
            self._data = copy.deepcopy(data)
```

I assume the second line wants to avoid deepcopying pyspark `DataFrames` (because it fails) without having to add pyspark as a kedro dependency, but other pyspark classes fail:

```python
# This code throws an exception
import pyspark.sql.functions as F
from kedro.io import MemoryDataSet
MemoryDataSet(F.col("my_column"))
```

I have thought about the following possible solutions to the problem and I'd like to hear your thoughts on it. I'm listing from least complete solution to most complete in my opinion:

1. **Add some comments** to the `_load` and `_save` methods of `MemoryDataSet` on why all that data type check and different types of copies are necessary
2. Instead for just checking for DataFrame type name, **check for more (or all) classes from the pyspark module** (this is assuming that effectively that line is there because of pyspark)
3. Add a parameter to `MemoryDataSet.__init__`  and `CachedDataSet.__init__` to **allow the user to specify which kind of copy will be used to cache the data**. Maybe a string with the options `["auto", "assign", "copy", "deepcopy"]` could work. 

Thank you! Looking forward to hear your comments

**Comment by ZainPatelQB** [comment]
Hi @MigQ2 👋! Thank you for raising this, I've tagged it with our internal number to track this and will raise it with the team on Monday to discuss.

I think in general we're trying to move away from having so many dependencies in Kedro and moving to a install-if-you-need model where the basic Kedro ships with nothing and you install dependencies as you use the relevant datasets.

My thoughts would be that I'd want to avoid checking on a per-library basis (pandas/pyspark/whatever else people use) which would probably necessitate a bunch of conditional and local imports to check. I quite like the look of your third solution, where if you don't specify the parameter, it defaults to the current implementation but you can specify the option if you need to.

**Comment by ZainPatelQB** [comment]
Pulling in @idanov who knows a little more about this. :)

**Comment by idanov** [comment]
Hey @MigQ2, the challenge with PySpark datasets is that they actually contain no data, due to the way Spark works. So when running a Kedro node, you are not executing your operations for spark, but rather just building the execution graph for Spark which executes the operations on your behalf when you decide to save your data. That means that operations like `CachedDataSet` are undefined for Spark, or at least not in the same way as for any other data you would like to pass around.

The thing we've done for `MemoryDataSet` is just a hack to allow people to continue building the graph across multiple nodes and eventually sneak in a checkpoint through the `DataCatalog` by saving the data to disk. Choosing the mode of copying the Python object of the Spark dataframe is not going to solve the issue, since the desired behaviour is to call the Spark action `dataset.cache()` which will keep your data in-memory. However that makes the code specific depending on the data type and not generalisable. That's why the `CachedDataSet` won't work for Spark.

We're rethinking some bits of our IO functionality and as part of that process we might try to provide better support for caching, since at the moment it is not officially supported by the team as it is a contrib module. In the meantime, if you want to have a custom `CachedDataSet` functionality, you could extend the current implementation and just add the option

**Comment by MigQ2** [comment]
Hi @idanov , thank you for your reply. To clarify a bit more, I **don't** want `CachedDataSet` to trigger the `pyspark.sql.DataFrame.cache()` method, but to cache the python object that contains the DAG and metadata, which is what kedro is now doing correctly for `pyspark.sql.DataFrame` objects. 
In my opinion, the current behavior for `DataFrame` is correct, but it's implemented in a very hacky way within the `save` method of `MemoryDataSet` as you commented. 

In my concrete case, the problem is that I don't want to cache a `DataFrame` but a different pyspark object: I have a `pyspark.ml.PipelineModel` object that I want to cache (again I want to cache the python object that contains the DAG, I don't want any pyspark cache method to be called) but fails because the implementation of `MemoryDataSet` tries to deepcopy my `PipelineModel`, which raises an exception. 

I hope after this comments and context my original post makes more sense. Please let me know if there's something I could clarify further

**Comment by ZainPatelQB** [comment]
Hi @MigQ2,

That's incredibly helpful, thank you! Your clarification about wanting to save the python object containing the DAG and that you want to cache the `pyspark.ml.PipelineModel` object has totally clarified things for us.

We've discussed it and think that implementing your solution 3 is probably the best way moving forward (keeps it generalisable for other objects that don't like being deepcopied).

**Comment by ZainPatelQB** [comment]
I'm closing this because we've implemented your suggestion in https://github.com/quantumblacklabs/kedro/commit/77dc8117685e7d33e5db6e3745a13edfd11d20b7 and should be releasing a new version anytime now! :)
