### ISSUE TITLE
[KED-1452] Create new Starter using Kaggle's Titanic dataset

### ISSUE THREAD

**Issue by yetudada** [quantumblacklabs/kedro#246]
## Description
- We have GitHub issues in other Kedro repositories
- Here is the link to this one: https://github.com/quantumblacklabs/kedro-examples/issues/22

**Comment by w0rdsm1th** [comment]
I'm gonna work on this one

**Comment by avidiotic** [comment]
Is the issue still open, since the referenced issue is closed?

**Comment by laisbsc** [comment]
> Is the issue still open, since the referenced issue is closed?

Hey @avidiotic! The referenced issue was closed since the example is no longer required for our docs.


You can still work on the project, though. But more on the terms described at issue #541. I.e., in case you would like to build a Kedro-example using the Titanic Dataset, we will be happy to add it to our list of community projects under the [Kedro community](https://github.com/quantumblacklabs/kedro-community/) repo.

Let me know if it still interests you 👍

**Comment by avidiotic** [comment]
Sure. I can do that. 👍

**Comment by Minyus** [comment]
Actually, I created a simple starter Kedro project using Kaggle's Titanic dataset at:
https://github.com/Minyus/kedro_sklearn

I didn't send a pull request because I knew the documentation was not enough to be merged.

**Comment by laisbsc** [comment]
> Actually, I created a simple starter Kedro project using Kaggle's Titanic dataset at:
> https://github.com/Minyus/kedro_sklearn
> 
> I didn't send a pull request because I knew the documentation was not enough to be merged.

I had no idea you had done this already, @Minyus. Sorry about that. I would appreciate if you would like to expand a little more on the docs of your project but in any case, would you like to add the link to the [Kedro community](https://github.com/quantumblacklabs/kedro-community/#where-can-i-find-more-example-projects-using-kedro) repo?


> Sure. I can do that. 👍
@avidiotic Are you still interested on building a Kedro example? You are welcome to choose another Dataset (not the Titanic one) and go from there :) Let me know if you need anything.


I will close this issue now.
