### ISSUE TITLE
Error when Loading Compressed JSON DataSet through the Catalog

### ISSUE THREAD

**Issue by uwaisiqbal** [quantumblacklabs/kedro#288]
I have a dataset defined in my DataCatalog which is a gzip compressed JSON lines file that I would like to load through Kedro using a JSONDataSet. I have the following definition in my DataCatalog:

```yaml
test_json:
  type: JSONDataSet
  filepath: "data/01_raw/test.json.gz"
  load_args:
    lines: true
    compression: 'gzip'
```
However, when I try and load this dataset through a Kedro ipython session with the command:

```python
df = catalog.load('test_json')
```

I get the following error message:

```
DataSetError: Failed while loading data from data set JSONDataSet(filepath=data/01_raw/test.json.gz, load_args={'compression': gzip, 'lines': True}, protocol=file).
'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

I did some digging and it turns out GZIP adds an additional byte character, [see here](https://stackoverflow.com/a/44660123/1112091).

Then, I decided to look under the hood of JSONDataSet's load function and I found the following in `kedro/io/json_dataset.py` lines 138-142: https://github.com/quantumblacklabs/kedro/blob/master/kedro/io/json_dataset.py#L138-L142
```python
    def _load(self) -> Any:
        load_path = get_filepath_str(self._get_load_path(), self._protocol)

        with self._fs.open(load_path, mode="r") as fs_file:
            return pd.read_json(fs_file, **self._load_args)
```

It looks as through by forcing the file to be read initially through the filesystem, it is complaining about the startbyte. Can I ask why there is an explicit need to read the file first and then invoke pandas? Couldn't this be done directly through
```python
return pd.read_json(load_path, **self._load_args)
```

That would resolve the issue I am currently having with reading the gzip compressed json file

**Comment by lorenabalan** [comment]
Hi @uwaisiqbal , good to see you back here! Thanks for a really well-written issue!

I believe the ability to pass a path object into `pandas.read_json()` is only possible since pandas 1.0.0. The older versions, which Kedro is compatible with, expect a string which is a valid JSON or a file-like object, which is why we go through `_fs.open(...)`. The string can also be a URL, but that's not something `get_filepath_str` returns, except  if there's an HTTP protocol.

We have an item on our backlog to make Kedro work with new, stable `pandas`, which will be included in the next release. Immediate workaround would probably be to have a custom dataset class to handle your case?

**Comment by uwaisiqbal** [comment]
Hey @lorenabalan, thanks for getting back to me.

Yup I have a custom dataset as a quick fix for this. Guess I'll just have to wait for the next release.

Thanks!

**Comment by andrii-ivaniuk** [comment]
Hi @uwaisiqbal,
Thank you that you reported this issue.

Answering your question: we are using `fsspec` for filesystem related operation to have a general approach in all the supported datasets. The gzip compressed JSON file is actually a binary file but we open it as usual file `mode="r"` that causes the problem.

We are planning to fix this issue in the nearest future. Now we decide how to fix it in the best way since there are a few approaches. One of them is to change the mode to `mode="rb"`.

**Comment by lorenabalan** [comment]
Hi everyone, this should be fixed by this commit and made available in the next release: https://github.com/quantumblacklabs/kedro/commit/8329f452b96bda4ca3a3cd2b30f71f261e6a8af8
I'll go ahead and close this issue for now, feel free to come back if it's still causing you problems.
