### ISSUE TITLE
Separate data storage from data format in IO classes

### ISSUE THREAD

**Issue by zacernst** [quantumblacklabs/kedro#31]
I'm worried about a potential proliferation of inconsistent IO classes, but I think we could avoid this by making a change to how IO classes are structured.

Right now, an IO class reads a specific file format from a specific type of storage. For example, `CSVS3DataSet`` reads a specific format (CSV) from a specific storage type (S3). This requires that if you want to read a CSV from a different storage type, you need to write a whole new class (e.g. CSVLocalDataSet).

There are at least two problems with this approach:

1. If there are `N` formats and `M` storage types, then we'd need `N*M` classes, which would slow down development and lead to inconsistencies in how the same file formats are read.
2. If we want to add support for a new file type, we can't just do this once. It would have to be repeated `M` times. Which is bad.

We're not feeling the pain of (1) and (2) yet because the project is still new. But as the number of use-cases grows, we'll feel an exponentially increasing level of pain.

## Positive suggestion

We can lay a foundation for avoiding these issues by separating the IO classes into two types: 

1. Classes for reading raw data, each of which inherits from a mix-in class. Let's call this ``KedroFileReader``.
2. A class for parsing data, each of which also inherits from a mix-in class. Let's call this ``KedroFileParser``.

We stipulate that every ``KedroFileReader`` class must provide a file-like object supporting the usual `read` methods, `open`, `close`, and contexts (`with foo as f:`). `KedroFileReader` classes would not know anything about how to parse the data -- they just provide a uniform set of methods for reading data.

``KedroFileParser`` classes would provide a `parse` method that takes a file-like object as input and returns whatever data structure is appropriate (e.g. a DataFrame).

Finally, when we want to (e.g.) read a CSV from S3, the class's entire definition is:

```
class CSVS3FileReader (KedroS3Reader, KedroCSVParser):
    def __init__(self, **kwargs):
        ...here we would call the __init__ methods for the two mix-in classes...
```

If something very tricky were necessary for a specific `KedroFileReader` and `KedroFileParser` combination, methods could be overridden and/or a new `__init__` method could do custom stuff and then call the class's `super`. So we would not lose any flexibility.

Happy to work on this myself and open a PR.

**Comment by kopytjuk** [comment]
At least for Azure and S3 we can implement `KedroFileReader` classes reading binary data and decode them in-memory in the `KedroFileParser` implementations both for text-readable (csv) and binary (parquet) kind of files.

**Comment by idanov** [comment]
@zacernst Thank you very much for opening a feature request for this. We've had a lot of discussions internally about this issue and there are pros and cons for the suggested approach as well as the current model.

In addition to what you mention about `N` formats and `M` storage types, I would add that there's at least three variables here: `data format` x `data location` x `loaded data type`. For example, `CSVLocalDataSet` loads `CSV files` x `from local file system` x `into Pandas`. Meanwhile `SparkDataSet` loads `multiple file formats` x `from local and remote file systems` x `into Spark dataframes`. If we dig deeper, we will find out that it is very hard to find a pattern which will be true for all `DataSet`s, especially when adding `SQLDataSet`, scraper `DataSet`'s which have only load methods, etc. Things get even more complicated if we add `Versioned` or unversioned to the mix. The user needs to know if a combination they provide is not only valid, but existing in the library.

Your suggestion to separate the concerns for `data storage` and `data format` would make the work for `Kedro` developers a bit easier for implementing some of the valid combination with smaller number of classes. Unfortunately it will also create the code for each separate combination more complicated and harder to understand, thus the barier for a user to implement the support for a new `format,storage,type,versioned` combination they need for their project will become much higher - now they need to understand quite a few internal concepts before they can become productive. Moreover, this abstraction will not work in all cases, e.g. `SQLDataSet` or even `SparkDataSet`, since we do not control the underlying implementations, which already have preexisting assumptions we need to accomodate for in our abstraction - there's no clear split between reader and parser for quite a lot of them.

The current implementation definitely has the drawback of adding too many classes for each data format and potential class explosion. However the benefit of the current system is that each class will be very simple on its own and the entry barrier for implementing a custom `DataSet` is very low. The number of assumptions this abstraction has is also quite small, so it provides greater flexibility.

It's not an easy task to find which abstraction can work best for `Kedro`, but my personal opinion is that the current `DataSet` abstraction is much more flexible, such that it can even allow the abstraction you suggest to co-exist on top of it. That would not be possible if we move all the way in the other direction though, since the suggested structure is much more rigid and we would need to force all use-cases into it.

Since there's a lot of interest in the community about this, we should revisit this discussion in the core team and see if we can find a loose model which can accomodate for both requirements, `ease of use` and `scalability of implementations`. A possible solution is to leave the current model as the recommended and standard way to implement things, but build the abstraction you suggest on top of it for the `DataSet`s which are well suited for that. This way we might be able to get the best of both worlds with sacrificing only a bit of understandability.

We really welcome your comments, so please feel free to keep the discussion here alive.

**Comment by 921kiyo** [comment]
I am closing this for now, but we might re-open it if more people express interest :)
