### ISSUE TITLE
Keep local-only DataSets such as CSVLocalDataSet

### ISSUE THREAD

**Issue by Minyus** [quantumblacklabs/kedro#343]
## Description
In the latest `develop` branch, local-only DataSets such as `CSVLocalDataSet` were removed.
Although the generalized DataSets in `kedro.extras.datasets` such as `CSVDataSet` support local use, I'd like to request to keep the local-only DataSets to allow avoiding to use `fsspec` package.

## Context
Some users do not want to or cannot use `fsspec` package due to potential bugs, performance, or security issues.

## Possible Implementation
Keep local-only DataSets.

**Comment by 921kiyo** [comment]
@Minyus Thank you for the request! Are you currently facing any issues with fsspec? If so, we would like to know the details so we might be able to help you with it.

**Comment by mzjp2** [comment]
I'm echoing @921kiyo in that I'd also be interested in knowing what deficiencies `fsspec` has for you. I'm also tagging in @martindurant who's the main maintainer over at [fsspec](https://github.com/intake/filesystem_spec) who may also be interested. If there are any issues, a potential avenue is to report them on the `fsspec` repo and get them resolved there, and we'd benefit downstream.

One of the reasons we liked `fsspec` was that it reduced both the maintenance burden of datasets because there were fewer of them and it was easier to contribute one dataset and benefit more people than having to submit more than one for different cloud systems. Bringing back local-specific versions of all or most datasets would negate the first benefit somewhat and so I think it's a big decision to make.

**Comment by martindurant** [comment]
I can understand any project now wanting to take on extra dependencies. However, fsspec is lighter than most, since it has no (required) dependencies of its own. For *local* files, most methods simply pipe through to `os`-module methods, so really what you get is the convenience of having the same API as the other storage backends.

(by the way, dask depends on fsspec, and pandas is [considering it](https://github.com/pandas-dev/pandas/pull/33549), if that can increase confidence)

**Comment by Minyus** [comment]
I haven't faced any issues due to `fsspec` yet.
(I reported a design issue of the new pandas datasets https://github.com/quantumblacklabs/kedro/issues/342 , but not related to `fsspec`)
I like the idea of using `fsspec` for Kedro's datasets too.
Now that I understand how `fsspec` treats local files, I'd like to migrate to the new datasets.
Thank you.

**Comment by mzjp2** [comment]
I'll go ahead and close this issue, after Martin's clarification of how `fsspec` handles local paths. Thank you all. :)
