### ISSUE TITLE
[KED-1662] Allow loading of multiple versions of the same dataset on a single node.

### ISSUE THREAD

**Issue by sansagara** [quantumblacklabs/kedro#350]
## Description
Allow a particular pipeline node to load multiple versions of a versioned dataset that may exist on storage, maybe up to a limit (last N versions)

## Context
Recently, i came up with a use case where i wanted to load all existing versions of a particular dataset on a single node for joining them into a big, fat dataset. I ended up using a workaround (more complex than it needed to be, tbh).
I guess this can also be useful for appending, comparing, etc.

## Possible Implementation
Specify a special syntax that can be used to tell a pipeline that multiple versions of a particular input are to be loaded. Maybe something like:

```
            node(
                func=lemmatize,
                inputs='int_articles:5',
                outputs='prm_articles',
                name="lemmatize"
            ),
```
Where `:5` means that the latest 5 versions are to be loaded. 
This would mean that the node function will be receiving a list of 5 datasets instead of a single one. It will be then need to be unpacked/traversed by the user.

I guess this might also require a new method to each of the AbstractDataset implementations, to be able to query the filesystem for existing versions. But it can be simply implemented at least for local filesystem-based files.

This can be implemented either with the help of lists/dicts or simply using kwargs. (Although it would mean that only a single dataset can be versioned for each node, and be placed at the end).

**Comment by 921kiyo** [comment]
@sansagara Thank you for the suggestion! We are interested in learning the use case a bit more :) 

> I wanted to load all existing versions of a particular dataset on a single node for joining them into a big, fat dataset

Could you elaborate the use case a bit more? Let's say you have 5 versioned data and each of them is slightly different (and most of them are the same). What happens when you join them all for duplicate and different values? Maybe a small example would be helpful for us to understand. And could you explain the workaround you did?

**Comment by sansagara2** [comment]
Sure NP. I'll explain the use case exactly.
We are doing scheduled scraps of websites that we store as Pandas CSV datasets on the RAW level. As with any website, each day you are going to get new information, and some will be gone. 

My use case is to still have a raw version with only the data for that particular day, as a versioned dataset you can go and look if you need to. Then, on the INT stage you would join them all together to have the whole data. I would simply concat them and remove duplicates using one of the ID columns. It's a simple procedure.

What makes the matters worse for my use case is the fact that i can not just append the INT version with the RAW version on a single node on each pipeline run due to the fact that Kedro checks for circular dependencies (DAG), thus i'm unable to have the INT dataset as both input and output of a node.

My workaround was to create a SQLlite database where i would insert all records and let the PK on the ID column handle old, existing records. It's actually useful on later stages to do some visualizations.

But anyways, the more i think about this feature request, the more it makes sense to me. It will definitely make dataset versioning a lot more useful on Kedro.  You could load multiple versions of a dataset without knowing the timestamp for the version.

I was pointed by a colleague to look into the Code API for `DataCatalog` instead of YML. I saw on the Docs that  I can specify a particular version to load, but did not see an option for loading N multiple versions, not knowing how much/which of them are.

**Comment by sansagara** [comment]
I got this feedback from another colleague about this feature request:

> I'd suggest a more pythonic syntax: `blablah:5` is confusing - `blablah[:5]` is more in tune with normal pythonic syntax and clearer for whoever is used to it.
> Then that could become `blablah[2:3]` or any slice at all

**Comment by gufodotto** [comment]
Hello there,

I second this request but I'd like to add a modification to the syntax enabling slice operator:

if a versioned catalog entryis written as:

entry[:5]
  ...

it would load the last 5 versions of it (and return them not joined, but as an ordered list, as suggested by the OP)

**Comment by 921kiyo** [comment]
@sansagara Sorry for being late in response, and thank you for explaining the use case!! I've logged your request and will discuss this feature internally :) Again, thank you for your suggestion!
