### ISSUE TITLE
[KED-1756] PartitionedDataSet to allow Empty Paths

### ISSUE THREAD

**Issue by tamsanh** [quantumblacklabs/kedro#394]
## Description
IncrementalDataSet currently supports having an empty path, so how can we also let PartitionedDataSet do the same?

## Context
Currently, if I'm using a PartitionedDataSet, I'm required to put something in the partitioned path. If it is empty, there is an inescapable Exception that is thrown when the pipeline is run.

In my opinion, verifying if data is available or should be done in a different layer other than the DataSet layer.

There are many times where data not existing is a valid case, and if we require the partitions to be non-empty, then extra complexity goes into ensuring that data exists, to satisfy the DataSet.

## Possible Implementation
1. Remove the raised exception.
2. Add an option inside of the `__init__` to `allow_empty`.

**Comment by DmitriiDeriabinQB** [comment]
Hi @tamsanh! Thank you for the feedback. You are absolutely right, as [documentation suggests](https://kedro.readthedocs.io/en/stable/04_user_guide/08_advanced_io.html#incremental-dataset-load), unlike `PartitionedDataSet` `IncrementalDataSet` does not raise a DataSetError if load returns no partitions.

Current design assumes that partitioned dataset points to a "static" location, where there should be some data. If no data is returned, we assume that being an error and raise rather than silently pass. Incremental data load, however, is dynamic by nature and may result in no partitions being available.

To consider suppressing this error, we would need to better understand your use case for why and when you still want to load empty partitioned dataset. Can you please elaborate more on that? Thanks!
