### ISSUE TITLE
Allow catalog in Python format in addition to YAML

### ISSUE THREAD

**Issue by Minyus** [quantumblacklabs/kedro#397]
## Description

I would suggest allowing declaring catalog datasets as a Python code in addition to YAML.

## Context

I personally like to use YAML, but it seems that forcing YAML format as catalog is becoming an obstacle for many Python users to start to use Kedro. 

Here are some examples new Kedro users suffered from YAML : 

- https://github.com/quantumblacklabs/kedro/issues/386
- https://github.com/quantumblacklabs/kedro/issues/387
- https://github.com/quantumblacklabs/kedro/issues/392

It is true that many Python users hesitate to learn YAML or Kedro's Templated Config.

## Possible Implementation

In addition to `catalog.yml`, accept `catalog.py` like this:

```python
# written in conf/base/catalog.py

from kedro.extras.datasets.pandas import CSVDataSet

catalog_dict = dict(
  foo_dataset = CSVDataSet(filepath="data/foo.csv"),
  bar_dataset = CSVDataSet(filepath="data/bar.csv"),
)
```

## Possible Alternatives

Provide a built-in hook to add catalog Python dict like this:

```python
from typing import Dict

from kedro.io import AbstractDataSet, DataCatalog
from kedro.framework.hooks import hook_impl


class AddCatalogDictHook:
    """ Hook to add data sets.
    """

    def __init__(
        self, catalog_dict: Dict[str, AbstractDataSet],
    ):
        """
        Args:
            catalog_dict: catalog_dict to add.
        """
        assert isinstance(catalog_dict, dict), "{} is not a dict.".format(catalog_dict)
        self._catalog_dict = catalog_dict

    @hook_impl
    def after_catalog_created(self, catalog: DataCatalog) -> None:
        catalog.add_feed_dict(self._catalog_dict)
```

My Kedro template using this hook is available at: https://github.com/Minyus/kedro_template

**Comment by mzjp2** [comment]
Hi @Minyus! Thanks for raising this.

I believe we already have some sort of support for this, documented here: https://kedro.readthedocs.io/en/stable/04_user_guide/04_data_catalog.html#using-the-data-catalog-with-the-code-api in the "Data Catalog with the Code API". Have you had a look through that and how does it differ from what you propose? Does it fit the need?

In terms of the `after_catalog_created` hook, @limdauto or @921kiyo can lend some more voices here. Our initial set of hooks were conservative because it's easier to provide new hooks than to remove ones.

**Comment by Minyus** [comment]
Hi @mzjp2 

I believe most of Kedro users want to use KedroContext, but the document (https://kedro.readthedocs.io/en/stable/04_user_guide/04_data_catalog.html#using-the-data-catalog-with-the-code-api) does not use KedroContext. 
It would be useful for unit testing though.

**Comment by tamsanh** [comment]
@mzjp2   The `after_catalog_created` hook does allow one to modify the catalog just fine.

@Minyus You should be able to create the pipelines in a separate class, and attach it to the context using hooks.

Ex:

```
class MyNewDataSets:

    @staticmethod
    @hook_impl
    def after_catalog_created(*args, catalog=None, **kwargs):
        for name, ds in dict(foo_dataset = CSVDataSet(filepath="data/foo.csv"), bar_dataset = CSVDataSet(filepath="data/bar.csv"),):
            catalog.add(name, ds)


class ProjectContext(KedroContext):
    hooks = (MyNewDataSets,)
    ....
```

**Comment by mzjp2** [comment]
Ah, I forgot we actually had a `after_catalog_created` hook 🤦‍♂️  and thought the proposal here was asking for us to add it, my bad

**Comment by tamsanh** [comment]
Ah, @Minyus , I misread your post. I understand, now. What you’re suggesting is that using a python file to generate catalogs should be allowed as an alternative _default_ option, so that inexperienced YAML users may choose to use that instead.

**Comment by Minyus** [comment]
Hi @tamsanh  , yes, your explanation sounds more concise than mine.

It is better to be friendly to both novice and expert users. 
(That's why I recommend your [YouTube videos](https://www.youtube.com/playlist?list=PLTU89LAWKRwEdiDKeMOU2ye6yU9Qd4MRo) in my package [here](https://github.com/Minyus/pipelinex#kedro) .)

**Comment by tamsanh** [comment]
Hey @Minyus, I was thinking about your notes regarding new users, and totally agree.  
For a bit of fun, I made a project that you may like. It's along the same vein as your work, but is focused more on beginners.

Rather than specifying catalog entries with python code, this plugin specifies plugins via the nodes themselves. What do you think? Would it help some of the users you have in mind? ☺️ https://github.com/tamsanh/kedro-wings

**Comment by Minyus** [comment]
Hi @tamsanh, thanks for sharing your `kedro-wings`.

Here are pros and cons I found.

Pros:

1. For major file extensions such as "csv", users do not need to specify the DataSet class.
2. Users can avoid repeating to specify the same directory using optional "root" args.

Cons:

1. Auto-completion by Python IDE (PyCharm, VSCode, etc.) for DataSet classes cannot be used.
2. To use a custom DataSet class, users need to find the correct "type" string (e.g. "src.datasets.my_dataset.MyDataSet") which could be troublesome for some new users.

While `kedro-wings` seems to be an interesting option and helpful for some Kedro users, catalog with Python code seems to be a straightforward option for majority of new Kedro users.

**Comment by tamsanh** [comment]
Hey, thanks for looking @Minyus. I appreciate that feedback, and I see what you mean: auto-completion by the IDEs is so useful, and being able to do auto complete for custom datasets is doubly so.

If that's the case, how about this API change?

![image](https://user-images.githubusercontent.com/1330789/83696316-b8f51f80-a62e-11ea-9c9e-b6fdb115f001.png)

Instead of just copying the config dictionary, it can also supports passing in the dataset class. That would cover both the valid concerns regarding auto-completion, and the config would also be supported if the class is placed under `type`.

**Comment by Minyus** [comment]
Hi @tamsanh , thanks for your suggestion.
In your example, the auto-completion seems to be limited to the DataSet class names.
Auto-completion can be used for *arguments* of DataSet classes if users can code like this:

```python
hooks = (
    KedroWings(
        {
            "foo_dataset": pandas.CSVDataSet(
                filepath="data/foo.csv",
                load_args=dict(float_precision="high"),
                save_args=dict(float_format="%.16e"),
            ),
            "bar_dataset": api.APIDataSet(
                url="https://raw.githubusercontent.com/quantumblacklabs/kedro/develop/static/img/kedro_banner.png",
                method="GET",
                timeout=1,
            ),
        }
    ),
)
```

**Comment by WaylonWalker** [comment]
@tamsanh KedroWings is really cool!  I tested it out combined with [`steel-toes`](https://github.com/WaylonWalker/steel-toes) and they work really well together

**Comment by limdauto** [comment]
Thanks everyone for this very interesting discussion. I think in the future, we are going to transition towards a composition-based API for `KedroContext`, in which you can supply your own catalog, runner, pipeline, etc. in a much more declarative way. In such a world, using a YAML-backed catalog should be straightforward.

In the mean time, I agree using Hooks either in a DIY fashion or through @tamsanh's fantastic kedro-wings is a very sensible approach. I'm going to close this issue but please feel free to re-open if necessary.

**Comment by crypdick** [comment]
@mzjp2 I used the [`Data Catalog with Code API`](https://kedro.readthedocs.io/en/stable/05_data/01_data_catalog.html#using-the-data-catalog-with-the-code-api) instructions to make a `catalog.py`, but now I'm trying to figure out how to add it to the main Kedro catalog. Following @tamsanh [tutorial on adding Datasets Programmatically to a Kedro Catalog](https://www.youtube.com/watch?v=CIRVpMqWEIs), I see how I can add entries to the main catalog by overloading `_get_catalog()`-- but how do I merge the catalog.py catalog with the main Kedro catalog?

**Comment by lorenabalan** [comment]
Hi @crypdick , just to clarify, are you using _only_ hooks now, or a combination of both? Ideally only hooks or only `_get_catalog()` method should suffice. The hooks should only be called once, unless you have multiple hook implementations that are adding the same datasets at some point.
On the off chance that adding same dataset names more than once is intentional, you could pass `replace=True` to your `catalog.add()` calls.

**Comment by crypdick** [comment]
@lorenabalan When I run just the hook:

```python
class CodeAPIDataSetHook:
    @staticmethod
    @hook_impl
    def after_catalog_created(catalog: DataCatalog) -> None:
        print("running hook")
        for name, ds in my_catalog_dict.items():
            catalog.add(name, ds)


class ProjectContext(KedroContext):
    ...

    hooks = (
        KedroWings(),
        KedroGreat(),
        CodeAPIDataSetHook(),
    )

    def _get_pipelines(self):
        return create_pipelines()
```
The hook appears to run multiple times:

![2020-08-19_10-49](https://user-images.githubusercontent.com/5415776/90643250-c1aaca00-e209-11ea-9383-d06d6c4cdeeb.png)

For now, I've fixed the issue by checking the catalog before I add:

```python
    def after_catalog_created(catalog: DataCatalog) -> None:
        already_loaded_datasets = set(catalog.list())
        for name, ds in my_catalog_dict.items():
            if name not in already_loaded_datasets:
                catalog.add(name, ds)
```
