### ISSUE TITLE
Allow projects without a conf directory

### ISSUE THREAD

**Issue by WaylonWalker** [quantumblacklabs/kedro#445]
## Description

With hooks out, such as kedro-wings, I no longer NEED a conf directory, especially for small projects.  For simple pipelines, it seems a bit much to have so many files and directories and deters users from starting small projects with kedro.  I would love to build out a starter without a conf directory, but kedro throws the following error

``` python
ValueError: Given configuration path either does not exist or is not a valid directory: <my-directory>
```

## Context
I think the ability to create very simple starters will yield an easier starting point for folks just getting into kedro.  Currently, if we follow the kedro-pandas-iris starter format users need to touch at least three files to add new features (catalog, node, and pipeline).  In my experience, this is so overwhelming for some that they step away and choose not to use the framework.

**Comment by 921kiyo** [comment]
Hi @WaylonWalker 

Thank you for opening the request. You could actually override conf directory through ProjectContext, as `conf` was defined inside KedroContext class attribute in https://github.com/quantumblacklabs/kedro/blob/master/kedro/framework/context/context.py#L218

Let us know if that will fix your issue :)

**Comment by WaylonWalker** [comment]
That actually helps a lot, but doesn't solve the exact issue raised here.

Is it possible to pass in `None` and avoid the conf loader all together?

**Comment by mzjp2** [comment]
If you want to avoid the `conf_loader` all together, I was thinking about overriding [`_get_config_loader`](https://github.com/quantumblacklabs/kedro/blob/9082b9b408abc899643282bd67f30493dd4cb83a/kedro/framework/context/context.py#L488) to return an empty `ConfigLoader`, but `ConfigLoader` will fail at instantiation if its `conf_paths` is empty 🤔

**Comment by Minyus** [comment]
I agree with @WaylonWalker . 
It would be more intuitive and reduce the learning cost for begineers to try Kedro if `conf` folder is optional rather than required.

**Comment by laisbsc** [comment]
Hello @WaylonWalker,

Thank you very much for your patience and suggestion. I have logged your request and will discuss this feature as soon as possible.
And please keep the suggestions/feedback coming. We truly appreciate it! Chat soon! :)

**Comment by WaylonWalker** [comment]
Thanks for logging this and providing us with an update @laisbsc!

**Comment by laisbsc** [comment]
Hello @WaylonWalker and @Minyus.  

Thank you very much for your suggestion :) We truly appreciate your feedback!

We had a chat about this and removing the requirements for the `conf` folder is not on our roadmap plans. Since the beginning, this was a design choice for Kedro and changing it would not be in conformance with our propositions.  

On the aspect of initial difficulty, we are currently working on providing more learning aids and making the learning curve less daunting for newcomers. We also think that the new community channel will help a lot on it.  

Again, thank you very much for all your support and contributions. I will close this ticket for now but please do not hesitate to message us in case you need anything further.

Cheers! :)

**Comment by WaylonWalker** [comment]
I completely understand.  This team has a much deeper understanding of a broader set of use cases and users than I do.  I appreciate the consideration and feedback.
