### ISSUE TITLE
GUI to handle workflow

### ISSUE THREAD

**Issue by bensdm** [quantumblacklabs/kedro#507]
## Description
Kedro is an amazing tool. However i am wasting time handling dataset inputs ouputs. It would be great if it was possible to do this with a GUI as it is possible in [kelp](https://kelp.app/) for instance

## Possible Implementation
We can maybe use kedro viz to not only visualize but also modify the pipeline

**Comment by yetudada** [comment]
Hi @bensdm! Thank you for this great suggestion. I would like to find out more about your feature request. What would you like to be able to do on this GUI?

**Comment by tomateit** [comment]
I'd like to join this request :) 
Kedro is a great tool, but for me manual creation of various node combinations is quite exhausting, especially when I have to run a lot of tests. Kedro viz is a great baseline, but it would be lovely if it had a bit more interactivity, like:
- mentioned above drag-and-drop feature
- hyperparams grid search
- automated node replacement (for a case I have a group of similarly working nodes and I'd like to find out which is the best)
- "launch pipeline" button (as well as partial pipelines separately) + some feedback like results logging
- a thing that really messes with me - possibility to exclude some nodes from pipeline. Currently I even cannot just comment out them from code, because the restriction on uniqueness of input/output names, and I have to keep two sets of names and keep 'em consistent along all pipeline.

Anyways, Kedro already helps me a lot, so thank you for it!

**Comment by yetudada** [comment]
Thank you so much for the feedback on this! We have something in mind that we'd like to look into for 2021 around this. In the meanwhile, please also check out the latest version of Kedro-Viz, we're moving into the code viewer domain with the addition of our new side panel which will eventually expand to show code. 

![kedro-viz](https://user-images.githubusercontent.com/43755008/99386519-82ece480-28ca-11eb-9d93-228d64d82968.gif)

**Comment by eilseq** [comment]
Also vouching for this solution, and willing to help. Suggestion: embed Kedro-Viz in desktop container (Electron/Tauri) to have access to file system and perform changes on action. Should be a reasonable effort considering that GUI/interactivity is mostly implemented by compiled HTML.
