### ISSUE TITLE
[KED-2201] Versioning in Pipeline Package

### ISSUE THREAD

**Issue by benhorsburgh** [quantumblacklabs/kedro#577]
## Description

I'm frustrated that I need to manually provide a version number every time I package a pipeline, because I already track that version number in the standard python way.

Let's say I have a modular pipeline as:

```text
/pipelines
   /my_modular_pipeline
      /__init__.py
      /nodes.py
      /pipeline.py
```

The contents of my `__init__.py` file is:

```python
__version__ = 0.5.1
```

When I run `kedro pipeline package my_modular_pipeline` by default it will always generate `my_modular_pipeline-0.1-py3-none-any.whl`, but I have just packages `0.5.1`! The current work around is to run `kedro pipeline package my_modular_pipeline --version=0.5.1` but this should be picked up automatically like every other python packaging utility.

## Context

Current kedro packaging is non-standard, and this is going to lead to bugs and headaches with building the correct versions of whl files.

## Possible Implementation
Read `__version__` in init, and where it exists, use that instead of the default.
Remove --version argument?

## Possible Alternatives
NA

**Comment by Sitin** [comment]
Hi, @benhorsburgh. Since I've also faced this problem, here is a simple fix involving minor changes in the `src/setup.py`:

First, discover the version of your package:

```python3
import importlib

package_version = importlib.import_module('<your package name>').__version__
```

Provide the correct version to `setup(version=version, ...)`.

This is not a framework issue but a flaw of the [default project starter](https://github.com/quantumblacklabs/kedro/blob/master/kedro/templates/project/%7B%7B%20cookiecutter.repo_name%20%7D%7D/src/setup.py#L49). However, I also think that it should be fixed there.

**Comment by lorenabalan** [comment]
Thank you for raising this and for your patience in getting this resolved. The fix has not been [merged](https://github.com/quantumblacklabs/kedro/commit/d082191966fc8a07cf6ef6837ea80add444e0efd) to `master` and will be made available in the next minor release. I'll go ahead and close this issue as resolved.
