### ISSUE TITLE
Errors when trying to contribute new extras feature

### ISSUE THREAD

**Issue by lucasjamar** [quantumblacklabs/kedro#594]
## Description
Hi! I am trying to create new extras feature by following these [steps](https://github.com/quantumblacklabs/kedro/blob/master/CONTRIBUTING.md#feature-requests). However I am encountering the following issues and I wonder if any them is going to stop me from correctly contributing a feature. In the docs it is specified that these commands need to run successfully. If they are going to be an issue, does anyone know how I could solve them?
Thanks

## Steps to Reproduce
1. Created new python 3.8 (also tried 3.7) virtual environment in anaconda.
2. Forked and cloned kedro repository
3. Ran: "make install-test-requirements"
4. Got first error message
5. Manually installed geopandas through "conda install geopandas". Based on this [answer](https://stackoverflow.com/questions/54734667/error-installing-geopandas-a-gdal-api-version-must-be-specified-in-anaconda).
6. Reran "make install-test-requirements"
7. Got second error message
8. Nonetheless ran: "make install-pre-commit"
9. Got 3rd error message
10. Nonetheless ran "make test-no-spark"
11. Got the third error message
12. Nonetheless ran "make build-docs"
13. Got the fourth error message

## Actual Result
After step 3 I got the following message

```
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\lucas\anaconda3\envs\kedro-37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\lucas\\AppData\\Local\\Temp\\pip-install-ury96kq4\\fiona\\setup.py'"'"'; __file__='"'"'C:\\Users\\lucas\\AppData\\Local\\Temp\\pip-install-ury96kq4\\fiona\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\lucas\AppData\Local\Temp\pip-pip-egg-info-lmd0rg07'
         cwd: C:\Users\lucas\AppData\Local\Temp\pip-install-ury96kq4\fiona\
    Complete output (1 lines):
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Which seems to have been solved with step 5. However, after running step 6, I get the following dependency issues:

```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

adlfs 0.2.5 requires fsspec<0.6.3,>=0.6.0, but you'll have fsspec 0.6.3 which is incompatible.
docker 4.3.1 requires pywin32==227; sys_platform == "win32", but you'll have pywin32 228 which is incompatible.
tensorflow 2.3.1 requires numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.2 which is incompatible.
trufflehog 2.1.11 requires GitPython==3.0.6, but you'll have gitpython 3.1.11 which is incompatible.
```
After step 8 I get:
```
An unexpected error has occurred: CalledProcessError: command: ('c:\\users\\lucas\\anaconda3\\envs\\kedro-37\\python.exe', '-mvirtualenv', 'C:\\home\\lucas\\.cache\\pre-commit\\repoo06rby0h\\py_env-python3.7', '-p', 'c:\\users\\lucas\\anaconda3\\envs\\kedro-37\\python.exe')
return code: 1
expected return code: 0
stdout:
    FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\lucas\\anaconda3\\envs\\kedro-37\\Lib\\venv\\scripts\\nt\\python.exe'

stderr: (none)
Check the log at C:\home\lucas/.cache\pre-commit\pre-commit.log
make: *** [Makefile:51: install-pre-commit] Error 1
```
After step 10 I get:
```
ERROR tests/extras/datasets/tensorflow/test_tensorflow_model_dataset.py::TestTensorFlowModelDatasetVersioned::test_version_str_repr[None-None-None-None-None]
FAILED tests/tools/ipython/test_ipython_loader.py::TestIpythonStartupDir::test_locate_no_project - AssertionError: as...
```

After step 12 I get:
```
./docs/build-docs.sh
make: ./docs/build-docs.sh: Command not found
make: *** [Makefile:39: build-docs] Error 127
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Conda version used: conda 4.9.0
* Python version used: Python 3.7.9 but also 3.8
* Operating system and version: Windows 10 Pro

**Comment by DmitriiDeriabinQB** [comment]
Error 1: You might need to install Fiona manually on Windows by running `conda install -c conda-forge fiona -y`
Error 2: It's not technically an error since `pip` does not break, it is merely a warning
Error 3: It might be related to the bug we encountered that `Virtualenv 20.*` [broke some of the pre-commit hooks](https://github.com/quantumblacklabs/private-kedro/blob/856cea8f459469c09e048e5f8968c848219c58d8/.circleci/config.yml#L38)
Error 4: I don't have anything to suggest here
Error 5: Kedro documentation won't build on Windows as we rely on shell scripts for that (but this is not required to start working on a feature)

To setup your dev environment on Windows you can (roughly) follow the steps in our CI: [`win_setup_conda`](https://github.com/quantumblacklabs/private-kedro/blob/856cea8f459469c09e048e5f8968c848219c58d8/.circleci/config.yml#L122), [`win_setup_env`](https://github.com/quantumblacklabs/private-kedro/blob/856cea8f459469c09e048e5f8968c848219c58d8/.circleci/config.yml#L136), [`win_setup_requirements`](https://github.com/quantumblacklabs/private-kedro/blob/856cea8f459469c09e048e5f8968c848219c58d8/.circleci/config.yml#L174).

Note that [not all our unit tests are runnable on Windows](https://github.com/quantumblacklabs/private-kedro/blob/856cea8f459469c09e048e5f8968c848219c58d8/.circleci/config.yml#L190), so the coverage won't be 100%

**Comment by mlisovyi** [comment]
I had the same problems trying to set up a dev environment on my windows laptop (linked above).
@DmitriiDeriabinQB all the links in your reply point to `private-kedro`, which we unfortunately can not access. Would it be possible to share information publicly?

Otherwise it's kind of frustrating to contribute for Windows users, which is a large fraction of corpo. I do not want to be the devil's advocate and i run Ubuntu on my private laptop but my work laptop uses Windows unfortunately

**Comment by mzjp2** [comment]
> I had the same problems (including problem at step 4) trying to set up a dev environment on my windows laptop (linked above).
> @DmitriiDeriabinQB all the links in your reply point to `private-kedro`, which we unfortunately can not access. Would it be possible to share information publicly?
> 
> Otherwise it's kind of frustrating to contribute for Windows users, which is a large fraction of corpo. I do not want to be the devil's advocate and i run Ubuntu on my private laptop but my work laptop uses Windows unfortunately

If you replace `private-kedro` with `kedro` in the URLs, they should work 😅

**Comment by mlisovyi** [comment]
Thanks. So trivial solution and yet so powerful!

Downgrading the version of virtualenv helped to install the git hooks.
However, running the hooks on a commit still doesn't work: [pre-commit.log](https://github.com/quantumblacklabs/kedro/files/5537041/pre-commit.log)

the actual environment looks like this: [conda_specs.txt](https://github.com/quantumblacklabs/kedro/files/5537051/conda_specs.txt)

at this tage it seems I will better try to install it on a linux machine rather then investing time into making it install on windows :(

**Comment by DmitriiDeriabinQB** [comment]
> Downgrading the version of virtualenv helped to install the git hooks.

@mlisovyi Does it mean that `make lint`, for example works for you on Windows? It may fail due to some linting errors, I just want to confirm that the command itself is runnable.

**Comment by mlisovyi** [comment]
Yes, `make lint` kind of worked, when executed in the terminal. "Kind of", because trufflehog anyway [failed for some unclear to me reason](https://github.com/quantumblacklabs/kedro/files/5546798/make_lint.log).

But in general pre-commit on windows works. I do use its hooks in other projects to run isort and black (and some othe basic hooks, but not linting)

**Comment by andrii-ivaniuk** [comment]
You can use [Circle CI configuration](https://github.com/quantumblacklabs/kedro/blob/424756dae498048094ebb00bb15674c88f31f7fd/.circleci/config.yml) as a guidance for how to set up Windows environment.

**Comment by mlisovyi** [comment]
Thanks @andrii-ivaniuk . Could you point at specific lines in the file or better add the instructions to the docs? For a beginner looking through ~500 lines of yaml is not a realistic option.

**Comment by andrii-ivaniuk** [comment]
https://github.com/quantumblacklabs/kedro/blob/424756dae498048094ebb00bb15674c88f31f7fd/.circleci/config.yml#L121

**Comment by andrii-ivaniuk** [comment]
@lucasjamar Do you have any problems with the Windows env setup? If no, could you please close the issue?
