### ISSUE TITLE
[KED-1878] Create an Avro dataset

### ISSUE THREAD

**Issue by yetudada** [quantumblacklabs/kedro#607]
## Description
Support [Avro](https://github.com/apache/avro) datasets as one of the supported DataSet formats to export a BigQuery table to Google Cloud Platform storage.

## Possible Implementation
Use the [Kedro documentation](https://kedro.readthedocs.io/en/stable/07_extend_kedro/01_custom_datasets.html) on how to create a custom DataSet.

**Comment by kislerdm** [comment]
Hi @yetudada, I'd be keen to commit to this issue in terms of the pydata'20 sprint. Thanks

**Comment by kislerdm** [comment]
@yetudada Hey Yetunde! I've submitted a PR. There is an issue with docs generation though. 

sphinx is screwing to figure the link between two modules of my codebase. One of the options to resolve it would be to adjust `https://github.com/quantumblacklabs/kedro/blob/master/docs/build-docs.sh` and run sphinx-build as

```bash
sphinx-build -c docs/ -ETan -j auto -D language=en docs/build/ docs/build/html
```
instead of 
```bash
sphinx-build -c docs/ -WETan -j auto -D language=en docs/build/ docs/build/html
```

Could you please confirm whether it's an acceptable solution. Thanks

**Comment by St-Hakky** [comment]
Hi. I want to use Avro dataset in my pipeline.

The PR is already reviewed and is it ready to merge? I am looking forward to using it!!
