### ISSUE TITLE
Appendable Excels not performed in the correct order

### ISSUE THREAD

**Issue by lucasjamar** [quantumblacklabs/kedro#630]
## Description
Appendable Excels not performed in the correct order

## Context
![image](https://user-images.githubusercontent.com/39372418/100718681-e80d0380-33bb-11eb-857b-cf63d2512b9c.png)

I have a simple pipeline where I read in three separate Excel sheets from the same xlsx, perform a task on each sheet, and rewrite the result to another xlsx. In my data catalog, "summary_quarter" is the main pandas.ExcelDataset and "summary_month" and "summary_week" are AppendableExcelDatasets of the same xlsx.
The problem is that Kedro is performing tasks on "summary_week" first. Naturally it throws an error because the xlsx initiated by "summary_quarter" does not exist yet.
I thought I could solve this problem by making an empty xlsx. However, this does not solve the issue because the results from "summary_week" are lost when the xlsx is overwritten by "summary_quarter".

I searched for a solution to force Kedro to start with a certain dataset but found nothing. If someone has a tip, id be really grateful if they could share it here.

Otherwise, I dont really have any ideas on how to solve this. Ideally, Kedro, by reading the order of appearance of the datasets in the catalog, should infer that quarter should be performed first, followed by month, then week.

## Your Environment
* Kedro 0.16.6
* Python 3.8
* Windows 10 Pro

**Comment by yetudada** [comment]
Hi @lucasjamar! Thanks for flagging this. I hope the other parts of Kedro have been okay for you. 

Can I play back if I understand what you're trying to do first? Is it: _"You have a single Excel spreadsheet that in this case has three sheets, `summary_quarter`, `summary_month` and `summary_week`. You want to process each sheet individually and then combine the three sheets in a single Excel spreadsheet."_ And the reason you can't do this is because: "The way the `AppendableExcelDataSet` works is that it expects a default ExcelDataSet to append to. So `summary_quarter` has to go first." 

If I got this right then I need to tell you that there is no way to specify explicit node order in Kedro at the moment since the datasets are the only defining factor in the execution order.

The workaround currently would be to add dummy dependencies between the nodes, something like:
```
node(make_pretty_df, summary_quarter, [summary_quarter_pretty, dummy_node1_out]),
node(make_pretty_df, [summary_week, dummy_node1_out], summary_week_pretty),
node(make_pretty_df, [summary_month, dummy_node1_out], summary_month)
```
`dummy_node1_out` doesn’t need to be registered in the catalog and can simply be `None`. Let me know if this resolves your issue and I'll close the ticket.

**Comment by lucasjamar** [comment]
Hi @yetudada ! Yes Kedro is great tool for my data science projects!
Yes you understood what it is I am trying to do
Ok I see. Thanks for the hack. I will add to my pipeline.

Many thanks!

**Comment by yetudada** [comment]
Awesome! Glad this is sorted! I'll close the ticket now.
