### ISSUE TITLE
[KED-2336] kedro clean

### ISSUE THREAD

**Issue by clstaudt** [quantumblacklabs/kedro#635]
## Description

A command that deletes all intermediate data sets created during a pipeline run, not unlike `make clean`. 

## Context

In order to debug pipelines it is often helpful to add intermediate outputs to the data catalog and write them to disk. However, "leftover" intermediate data sets can be a source of bugs when developing pipelines. Suppose you rewired the pipelines and made an error, but it does not show up as pipeline failure because you forgot to delete an old intermediate data set.

## Possible Implementation

One could perhaps mark data sets as "intermediate" in the sense of fully managed by pipelines - never modified or replaced except by `kedro run`.  Then `kedro clean` could automatically delete those.

## Possible Alternatives

Manually deleting these datasets from the data folder.

**Comment by DmitriiDeriabinQB** [comment]
@clstaudt thank you for the suggestion. Currently, the `DataSet` class in essence exposes only 2 methods to its users - `save` and `load`. Programmatic deletion would require an extension of the API for all datasets, since those should now also know how to delete the data. Although it might be easy for some filesystems (like the local one), for other implementations (like HDFS, for example) might be a bit trickier.
I will log this request for the technical assessment, however I believe there are some easier ways to achieve what you want if you only deal with local files:
1. When configuring intermediate datasets, put them all into `data/02_intermediate` and then just clean the whole folder altogether (`rm -r data/02_intermediate/*`)
2. Assign a specific [layer](https://kedro.readthedocs.io/en/stable/03_tutorial/06_visualise_pipeline.html#interact-with-data-engineering-convention) to all your intermediate datasets that need to be deleted and then iterate through `DataCatalog.datasets` property to remove the ones with the layer specified.
3. You can also use the `Pipeline` object to retrieve all intermediate datasets: `pipeline.all_inputs() & pipeline.all_outputs()` and then remove those.

**Comment by clstaudt** [comment]
Thanks for the comment. From the suggested alternatives I believe only 3. is a potential solution to my problem, namely deleting all outputs of a pipeline programmatically. Can you give a bit more example code to show how this can be done?

**Comment by clstaudt** [comment]
And if  `pipeline.all_outputs()` can be deleted programmatically - isn't that the implementation of `kedro clean`?

**Comment by DmitriiDeriabinQB** [comment]
> example code to show how this can be done

Sure, first run [`kedro ipython`](https://kedro.readthedocs.io/en/stable/11_tools_integration/02_ipython.html) from your project root, then

```python
from pathlib import Path
from shutil import rmtree

pipeline = context.pipelines["<pipeline_name>"]
intermediate = pipeline.all_outputs() & pipeline.all_inputs() & catalog._data_sets.keys()

for dataset_name in intermediate:
    filepath = Path(catalog._data_sets[dataset_name]._filepath)
    if filepath.is_file():
        filepath.unlink()
    elif filepath.is_dir():
        rmtree(filepath)
```

**Comment by clstaudt** [comment]
Restricting this to only outputs would be a useful feature to have on the command line:

`> kedro clean
`
`>kedro clean --pipeline_name=my_pipeline`

**Comment by mzjp2** [comment]
I suspect if this were to exist, then

`kedro pipeline clean <pipeline-name>` makes more sense and fits into the already existing pipleline CLI group. 

> And if `for pipeline in all_pipelines: pipeline.all_outputs().delete()` can be done - isn't that the implementation of `kedro clean`?

From what I understood, the issue is that `.delete()` doesn’t quite exist. It’s easy to do for local filepaths because you can delete a local filepath easily yourself, but adding this method to all datasets that live on S3/HDFS/etc... is a large-effort piece of work.

If you had a dataset living on S3, the `.unlink()` would become an S3 API call (or I suppose using the underlying `fsspec` `.delete()` mechanism(?)

**Comment by DmitriiDeriabinQB** [comment]
> the issue is that .delete() doesn’t quite exist

Exactly that @mzjp2. We would need to introduce `AbstractDataSet.delete()` + the implementations for all the datasets.

**Comment by clstaudt** [comment]
I am quite ignorant about the technicalities of remote storage, but let me be naive: If Kedro can create those data sets, Kedro can surely delete them too.

**Comment by lorenabalan** [comment]
Possibly related to https://github.com/quantumblacklabs/kedro/issues/406
