### ISSUE TITLE
PartitionedDataSet + dask.ParquetDataSet: every chunk is a key

### ISSUE THREAD

**Issue by crypdick** [quantumblacklabs/kedro#639]
## Description
When loading a chunked ParquetDataSet saved as a PartitionedDataSet partition, each chunk is given it's own key but the "parent" dataframe is not. I think the fundamental issue is that if I save `dd.to_parquet(chunked_ddf, fpath)` it has to be loaded with `dd.read_parquet(fpath + "/*.parquet")` and Kedro doesn't have conditional logic to handle chunked datasets. 

## Context
We are chunking because our output datasets are terabyte-scale. We want to load the entire Dask dataframe with the Kedro catalog. There is no apparent way to do that: the catalog only gives us the option to load individual chunks/Parquet shards. Instead, we have to manually load our data without Kedro using `dd.read_parquet("s3://path/to/dataset_name/partition_name/*.parquet")`.

## Steps to Reproduce
1. define dataset: 
```python
PartitionedDataSet(
    path="s3://BUCKET/07_model_output/dataset_name",
    dataset={"type": "dask.ParquetDataSet", "load_args": {"index": "img_url"}}
    )
```
2. save Dask dataframe to `dataset_name` as `{partition_name: ddf}`
3. load `dataset_name` & list keys.

## Expected Result
PartitionedDatasets to have one reference for each Dask dataframe stored, where each partition key looks like `partition_name/*`

## Actual Result
There is no reference to the whole dataframe; instead, each chunk (and Dask metadata) has its own partition key:

![image](https://user-images.githubusercontent.com/5415776/101668478-5cd0e500-3a2f-11eb-861b-d01c3bcec020.png)

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): `kedro, version 0.16.5`
* Python version used (`python -V`): `Python 3.7.4`
* Operating system and version: `Ubuntu 20.04.1 LTS`

cc @daavidstein

**Comment by deepyaman** [comment]
I don't have an answer (sorry), but I noticed this issue while implementing versioning for `PartitionedDataSet`.

Partition discovery in `PartitionedDataSet` takes an end-of-path-first view. As you've found, this won’t work reading back something like Spark Parquets (or anything where the dataset writes to a folder structure rather than a file). Might have to rethink partitioning/enforce structure from the provided path like Spark does to support that.

As a thought exercise, what would file paths for a versioned `PartitionedDataSet`, where each dataset has a folder structure, look like?
