### ISSUE TITLE
Dependencies can be added via https URL but building documentation fails

### ISSUE THREAD

**Issue by nblumoe** [quantumblacklabs/kedro#675]
## Description
Dependencies can be added to `requirements.in` via a HTTP URL and `kedro install` will install them correctly. `kedro build-docs` will fail with an error though.

## Context
I added a spacY model to my `requirements.in` and can use it in my nodes. When I try to build the documentation for the kedro project, I encounter an error.

## Steps to Reproduce
1. Have a kedro project
2. Add `https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-2.3.1/en_core_web_lg-2.3.1.tar.gz#egg=en_core_web_lg` to `requirements.in` (see [spacy docs](https://spacy.io/usage/models#models-download)
3. Run `kedro install` and optionally use the model that was installed to verify the installation
4. Run `kedro build-docs`

-> encounter error

## Expected Result
The documentation should get build.

## Actual Result
The CLI exits with an error:

```
    ERROR: Command errored out with exit status 1:
     command: /Users/bar/miniconda3/envs/foo-kedro-search-terms/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/rm/7dw9bw5d5pj7lg41n5j77mww0000gn/T/pip-req-build-6eyfeosk/setup.py'"'"'; __file__='"'"'/private/var/folders/rm/7dw9bw5d5pj7lg41n5j77mww0000gn/T/pip-req-build-6eyfeosk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/rm/7dw9bw5d5pj7lg41n5j77mww0000gn/T/pip-pip-egg-info-g1cc9ux5
         cwd: /private/var/folders/rm/7dw9bw5d5pj7lg41n5j77mww0000gn/T/pip-req-build-6eyfeosk/
    Complete output (1 lines):
    error in kedro_search_terms setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Parse error at "'://githu'": Expected stringEnd
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.17.0
* Python version used (`python -V`):  3.7.9
* Operating system and version: macOS 10.15.7

**Comment by mzjp2** [comment]
I did a little bit of investigation, and this is a bit of a can of worms. Within your Kedro project, your `src/setup.py` files reads in `requirements.txt` and puts that in the `install_requires` section of your Python package wheel. The `kedro build-docs` commands calls `pip install src/[docs]` which tries to parse this `install_requires` section.

However, since your `requirements.txt` contains this HTTPs URL, it gets passed into the `install_requires`, but _setuptools_ doesn't like (see this [SO question](https://stackoverflow.com/questions/64482089/python-setup-py-dependency-as-url-to-tar-or-git))

A hacky workaround for now if you need to get this working _right now_ is commenting out the `install_requires` section of your `src/setup.py` or installing your documentation requirements yourself and then modifying your `kedro_cli.py::build_docs` command (by overwriting the one imported from Kedro) to skip the docs requirements installation).
