### ISSUE TITLE
[KED-2452] xlrd cannot read .xlsx files from version 2.0.1

### ISSUE THREAD

**Issue by monkeyclass** [quantumblacklabs/kedro#687]
An issue arises when trying to read from an .xlsx file, when the engine forced is xlrd, which since version 2.0.1 no [longer supports it](https://xlrd.readthedocs.io/en/latest/).

Instead if engine is set to openpyxl, it will be possible to read these. Alternative, do not specify the engine, and [let pandas decide on its own, which is should be capable of](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html).

https://github.com/quantumblacklabs/kedro/blob/46a4da6dbfc920dbbc8da418a16305915631bac2/kedro/extras/datasets/pandas/excel_dataset.py#L70

**Comment by monkeyclass** [comment]
Created draft pr #688

**Comment by datajoely** [comment]
Hi @monkeyclass thanks for raising this - I was half way through raising a bug before I saw your draft PR! 

Let's wait for CI to finish, there is a chance we need to make add `openpyxl` to `requirements.txt` and possibly add a test.

**Comment by lorenabalan** [comment]
Hi @monkeyclass , this has been addressed in https://github.com/quantumblacklabs/kedro/commit/247aaf18d885c462f7374bea994745d923ddd2e3

We classified this as a breaking change because given the same environment, upgrading kedro would make the project stop working (`kedro run` fails) unless users already had `openpyxl` installed.

There are workarounds to get this done in a project in the meantime until 0.18 is released - specifying `engine` in a dataset's definition in `catalog.yml` and adding `openpyxl` in the `requirements.in` (or .txt) of the project.

Hope this makes sense, and thank you for raising!
