### ISSUE TITLE
[KED-2509] Python 3.9 support

### ISSUE THREAD

**Issue by jaklan** [quantumblacklabs/kedro#710]
## Description
Kedro doesn't support Python 3.9, today's release (0.17.1) hasn't changed that. Is there any specific reason or can we expect that soon?

**Comment by MerelTheisenQB** [comment]
Hi @jaklan, thanks for raising this. We are indeed planning on adding support for Python 3.9 soon. Hopefully in the next release or the one after.

**Comment by cpoptic** [comment]
Can confirm Kedro 0.17.2 not working with Python  3.9.

**Comment by MerelTheisenQB** [comment]
Hi @cpoptic, we haven't added support for Python 3.9 yet. We'll make sure to add it in the release notes so you'll know when it's there 😄

**Comment by lorenabalan** [comment]
Hi @jaklan @cpoptic - it turned out we couldn't do this without changing the engine for our `pandas.ExcelDataSet` to be `openpyxl`, which is a breaking change for kedro. As a result, this has been implemented on `develop` and will be made available on the next major release 0.18.0. As an FYI, we are also looking at removing support for Python 3.6 for the same release.

I'll go ahead and close this as resolved, thank you for your patience! 🙏

**Comment by bbreton3** [comment]
Any news on python 3.9 support ?

**Comment by datajoely** [comment]
@bbreton3 we're nearly there - in the meantime you can follow these steps (the only thing that will break will be `pandas.ExcelDataSet` requiring `openpyxl` not `xlrd`)
https://github.com/kedro-org/kedro/discussions/1117#discussioncomment-1822667

**Comment by datajoely** [comment]
For anyone arriving here 3.9 and 3.10 support were just officially released :)
