### ISSUE TITLE
Kedro 0.17.2 cannot find s3fs

### ISSUE THREAD

**Issue by crypdick** [quantumblacklabs/kedro#749]
## Description
Upgrading from 0.17.0 to 0.17.2 results in the following error when running `kedro pipeline list`:

```
kedro.framework.cli.utils.KedroCliError: Unable to instantiate Kedro session.
Error: Install s3fs to access S3
Run with --verbose to see the full exception
Error: Unable to instantiate Kedro session.
Error: Install s3fs to access S3
```

When I try the `--verbose` flag as suggested, I get `no such option`. I checked `pip list` and I indeed had `s3fs==0.6.0`. I tried pip uninstalling and reinstalling s3fs and fsspec, and starting with a fresh venv. No dice. Downgrading kedro to 0.17.0 (and s3fs 0.4.2) solved the issue.

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used 0.17.0
* Python version used (`python -V`): 3.8.5
* Operating system and version: Ubuntu 20.10

**Comment by lorenabalan** [comment]
Hi @crypdick - I've not been able to reproduce your issue. Indeed the only guarantee we have around `s3fs` atm is up to 0.4.2 https://github.com/quantumblacklabs/kedro/blob/d5f33273c455171e377693b4cd9f109eafda8a82/setup.py#L44

However trying out with 0.6.0  didn't seem to run into problems, so I believe it has something to do with the project's requirements rather than with core kedro. 

Steps:
1. conda create -n debugging python=3.8.5 -y
2. conda activate debugging
2. pip install kedro==0.17.0
3. kedro new -s pandas-iris && cd to new project
4. kedro pipeline list ✅ 
5. pip install -U kedro
6. kedro pipeline list ✅ 
7. pip install s3fs==0.4.2 (or 0.6.0)
8. kedro pipeline list ✅

**Comment by crypdick** [comment]
It seems that pip-tools does not respect Kedro's `s3fs<0.5` requirement. My compiled requirements.txt ends up with `s3fs[boto3]==0.6.0`.

Steps to reproduce:

```
virtualenv venv --python=python3.8
source venv/bin/activate
pip3 install --ignore-installed pip-tools awscli PyYAML
pip-compile --upgrade src/requirements.in
pip-compile --upgrade src/requirements_dev.in
pip-sync src/requirements.txt src/requirements_dev.txt
pip3 install -e src/
pip3 install -U anyscale
pip list |grep s3fs  # s3fs==0.6.0
kedro pipeline list # ImportError: Install s3fs to access S3
```

Full requirements{*.in, *.txt} files: https://gist.github.com/crypdick/855b2c7283ff0388144669d78d0fc5d6

**Comment by Soufraz** [comment]
Hello. I am facing the same problem. Is there any temp solution to use s3 in datacatalog? Some downgrade to another kedro version or something like that.

My versions:
python 3.8
kedro==0.17.3
s3fs[boto3]==0.4.2

I tried with kedro 0.17.0 and python 3.7 either.
