### ISSUE TITLE
`kedro new --starter` no longer works for non official repos with Kedro>=0.17.0

### ISSUE THREAD

**Issue by lucasjamar** [quantumblacklabs/kedro#760]
## Description
I created a kedro starter for my company as a way to encourage colleagues to write their code with Kedro.
It used to be based on the Pandas Iris starter for kedro<=0.16.6.
I migrated the template such that it works with Kedro>=0.17.0.
However, now when I do `kedro new --starter=<my-repo>`, I get the following error:

![image](https://user-images.githubusercontent.com/39372418/117122930-afbc8780-ad96-11eb-85ea-e0ffee3f821e.png)

In this example, I cloned the pandas-iris to my github page as a public repo so the issue is not the use of a private repo.

## Steps to Reproduce
1. `pip install kedro>=0.17.0`
2. `kedro new --starter=https://github.com/lucasjamar/pandas-iris`

This issue does not happen if you use a local starter, eg: `kedro new --starter=./myfolder/pandas-iris`
Funny enough, when I install kedro==0.16.6 and run `kedro new --starter=https://github.com/lucasjamar/pandas-iris`, I dont have this issue.
I think this has to do with the fact that previously, the kedro starters each were there own [repo](https://github.com/quantumblacklabs/kedro-starter-pandas-iris) and now they are grouped together in https://github.com/quantumblacklabs/kedro-starters.
Im guessing the CLI would need to be modified for this to be fixed.

Many thanks,

**Comment by AntonyMilneQB** [comment]
Hello @lucasjamar. Thanks for bug report and sorry for the difficulty. This is actually not a bug but a badly documented feature with unhelpful error message. We're looking to improve this to make it a bit more obvious.

What's happening here is that kedro is looking to checkout a starter with tag `0.17.3` (since that's the version of kedro you have installed) but can't find that in your repo. The kedro version is effectively the default value of the command line `checkout` parameter, which specifies which branch/commit/tag to checkout. It works locally because this parameter only has an effect when looking at git repos and doesn't change anything if using a local directory.

So there are two possible fixes:
1. create a new tag/branch called `0.17.3` in your repo. This is a good option if you will be updating your template as kedro release new versions and you want to maintain compatibility for people using your template with different versions of kedro
2. specify that you want to checkout `master` when you use the starter: `kedro new --starter=https://github.com/lucasjamar/pandas-iris --checkout=master`

**Comment by lucasjamar** [comment]
Hi @AntonyMilneQB ,

Thanks for the explanation

**Comment by lucasjamar** [comment]
Hi @AntonyMilneQB ,

Thanks for the explanation! Now that you mention it, the tag functionality is really useful. Thanks. Ill look into contributing to the docs if thats ok :) .
