### ISSUE TITLE
Error when running pipeline with TemplateConfigLoader

### ISSUE THREAD

**Issue by selalamiTF** [quantumblacklabs/kedro#789]
## Description
When running a pipeline, Kedro loads the conf of all the defined pipelines. When doing a check on params, it ends up checking params from other pipelines which are not necessarily used in the current one. This ends up on an error when doing Kedro run --pipeline pipeline_name. The error is `ValueError: Failed to format pattern '${other_pipeline_param}': no config value found, no default provided`

## Context
I have two pipelines. Each one with it's own conf directories. I use a TemplatedConfig Loader to fill out catalog.yml with some parameters

## Steps to Reproduce
1. Use Kedro pipeline to create two pipelines 
2. Create in conf directory two pipelines directories each one with catalog.yml
3. In one of the catalog.yml use a parameter that is not used in the other catalog.yml  
4. use Kedro run --pipeline <pipeline_name_without_params> --params  to run one of the pipelines

## Expected Result
Run pipeline using the appropriate params

## Actual Result
Error because it expects to have all the parameters even if its not used
```
`ValueError: Failed to format pattern '${other_pipeline_param}': no config value found, no default provided`
```

```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): kedro, version 0.16.6
* Python version used (`python -V`): Python 3.7.10
* Operating system and version: MacOS Mojave 10.14.6

**Comment by ignacioparicio** [comment]
Hi @selalamiTF and thanks for opening the issue!

The way [`TemplatedConfigLoader`](https://github.com/quantumblacklabs/kedro/blob/master/kedro/config/templated_config.py#L168) is built, it recursively searches for strings that look like `${expr}` in all values it loads (inc. catalog paths, parameters etc.). It then maps such expressions with globals, and raises a `ValueError` (like the one above) when an instance of `${expr}` cannot be mapped.

If you'd like just _some_ params/catalog entries that depend on globals to be populated (so that it doesn't error out when a mapping is missing), the easiest solution is to [use different environments](https://kedro.readthedocs.io/en/latest/04_kedro_project_setup/02_configuration.html#additional-configuration-environments). This way, entries in the catalog/parameters that aren't part of the environment under consideration won't be loaded by `TemplatedConfigLoader`. Put differently, Kedro doesn't selectively load params/catalog entries based on _which pipeline is being run_, but based on _which environment is being used_.

Would using environments satisfy your use case?

**Comment by selalamiTF** [comment]
Hello @ignacioparicio ,
Thank you for getting back to me.
Yes using different environments would be a good workaround to solve this. Is there a reason why conf loading logic doesn't account for pipelines ?
I would like to point out that it would be a good idea to implement loading conf from an env based on a pipeline. To do this, conf are already sorted by pipeline. So my current solution is to change to the `_get_catalog` function to take the pipeline name as a parameter and modify the value passed to config loader : 
```python
        pipeline_catalog = "**/catalog*"
        if pipeline_name:
            pipeline_catalog = f"**/{pipeline_name}/catalog*"
        logging.info("Loading catalog info using %s", pipeline_catalog)
        conf_catalog = self.config_loader.get("catalog*", "catalog*/**", pipeline_catalog)
```

**Comment by ignacioparicio** [comment]
Thanks for your input and for sharing the code snippet! In a generic case, parameters can also be templated variables (i.e. depend on globals), so implementing this logic of selectively loading would be a bit more complex: we would also have to figure out which parameters are needed for the nodes about to be run, and then apply [format_object](https://github.com/quantumblacklabs/kedro/blob/master/kedro/config/templated_config.py#L194) just on those. It definitely could be done, but I'd argue that this is _likely_ not a priority the following two options exist:
1. Use run environments (which is Kedro's encouraged way of selectively loading config)
2. Set a dummy value for `other_pipeline_param` (if for whatever reason 1. is not an option _and_ we need to use a global we don't have)

If you still think this is important and have the time, we'd be very happy if you wanted to raise a PR to contribute with the additional feature :)
