### ISSUE TITLE
Request documentation on best practises when debugging kedro cli commands in a pycharm environment

### ISSUE THREAD

**Issue by roumail** [quantumblacklabs/kedro#817]
## Introduction

I am trying to generate a project using `kedro new --starter` and see a cookiecutter error that I would like to investigate in more detail by stepping through the code line by line

## Background

Being able to step inside the code is invaluable for better understand the error. 

## Problem

There's a lot of code to work through to get to the core functionality that actually creates the new project repo using the commands we pass on the cli. I'm unable to access those functions directly because then a number of initialization steps are not present. For example, context is missing, so on.

**Comment by datajoely** [comment]
Hi @roumail do you want to join us on Discord and it will be easier to debug?
https://discord.gg/akJDeVaxnB

**Comment by roumail** [comment]
Hi Joel! Thanks for the quick turn around - i'm just about to enter a call so I won't be able to join right away. 

The work around I use for moment is to A) use either post mortem debugging by executing the cli commands on the command line or B) set pdb.set_trace() inside the kedro codebase right before the line where I have the error. These solutions work, but then you're losing the power of pycharm debugging

**Comment by AntonyMilneQB** [comment]
Hi @roumail, I've reworked the implementation of `kedro new --starter` quite a bit recently so would be curious to hear what the problem is here. To debug it while developing, my approach is to set up a run configuration [as per this guide](https://kedro.readthedocs.io/en/stable/09_development/02_set_up_pycharm.html#debugging). You can put PyCharm breakpoints in the source code of kedro in site-packages and it should still work. Alternatively, if you want to have it more easily accessible you can `pip install kedro --target=. --no-deps` to install it into your current working directory rather than site-packages.

**Comment by datajoely** [comment]
Agree with everything @AntonyMilneQB says - the other hacky solution is to follow this sort of guide from the Jetbrains side that could allow you to invoke the PyCharm debugger from python code

https://www.jetbrains.com/help/pycharm/remote-debugging-with-product.html#remote-debug-config

**Comment by roumail** [comment]
This is great - exactly what I was looking for. I'm going to try these solutions out!
