### ISSUE TITLE
[KED-2695] docs redirects

### ISSUE THREAD

**Issue by WaylonWalker** [quantumblacklabs/kedro#857]
Each time a docs page changes name I have to change all my links to the docs to ensure they are working.  My guess is that there are quite a number of articles out there that just have broken links to the kedro docs.  Here are some that I had to fix this morning.  It would be a better experience for the end-users if there was a 301 to take them to the new page seamlessly.  Having someone's first experience with kedro be a broken link from a blog post isn't painting a good picture.

## Errors I found recently

Here are the URLs I recently had to fix.

https://kedro.readthedocs.io/en/stable/13_deployment/04_argo.html - 404
https://kedro.readthedocs.io/en/stable/10_deployment/04_argo.html

https://kedro.readthedocs.io/en/stable/10_deployment/08_aws_sagemaker.html - 404
https://kedro.readthedocs.io/en/stable/10_deployment/09_aws_sagemaker.html

https://kedro.readthedocs.io/en/stable/02_getting_started/04_hello_world.html - 404
https://kedro.readthedocs.io/en/stable/02_get_started/03_hello_kedro.html

https://kedro.readthedocs.io/en/latest/04_user_guide/15_hooks.html - 404
https://kedro.readthedocs.io/en/stable/07_extend_kedro/02_hooks.html

https://kedro.readthedocs.io/en/stable/04_user_guide/04_data_catalog.html - 404
https://kedro.readthedocs.io/en/stable/05_data/01_data_catalog.html

**Comment by lorenabalan** [comment]
Hi @WaylonWalker , thank you for raising this!! There's actually already a ticket on our backlog to investigate how to solve this in sphinx/readthedocs! We'd love to hear if anyone has any experience with [sphinx-redirects](https://pypi.org/project/sphinx-reredirects/) or if you have alternative suggestions for what we should look at. As always, we welcome PRs if anyone has a bit of time to spend on it. 🙌

**Comment by WaylonWalker** [comment]
I have never used spinx-redirects before.  I read through [user-defined-redirects](https://docs.readthedocs.io/en/stable/user-defined-redirects.html) from read the docs, and they have a way to do it in the admin panel, but suggest sphinx-redirects at the very end.  spinx-redirects seems like a better solution as it can be included in any pr that changes the name of a docs page.

**Comment by WaylonWalker** [comment]
I just played with sphinx-redirects for a little bit and was unsuccessful at getting it to work.  First I had to turn off treat warnings as errors, a PR to sphinx-redirects would be required to set parallel reading explicitly in the plugin.  Next the plugin did not seem to work well with subroutes very well.

I tried to redirect 04_argo with the following redirect.

``` python
redirects = {
    "13_deployment/04_argo.html": "10_deployment/04_argo.html",
}

```
The result I got locally was http://localhost:8000/10_deployment/04_argo.html -> http://localhost:8000/13_deployment/10_deployment/04_argo.html, notice the extra directory in there.  I think this is going to get more complicated when adding in /$lang/$version into the route.


I'll submit what I have so far as a draft pr if anyone wants to see what I have so far.

**Comment by AntonyMilneQB** [comment]
Hey @WaylonWalker, thanks for looking into this! Having spent way too much time myself fiddling around with sphinx and sphinx plugins recently, I am inclined to believe that if you couldn't get it working easily then unfortunately there's probably not much hope :( 

Most of our redirect problems come from the fact that our documentation is numbered. This helps with editing and browsing documentation source, since when editing files appear in the same order as in the docs, but it does mean that as soon as you add a new section, all the subsequent pages need to be renumbered and that breaks all the links. So if we did get `sphinx-redirects` working I think that over time it would grow to be a very long and complicated list of redirects that we need 😬 

What I would suggest is that we remove all the numbering from our documentation in one big breaking job (for 0.18 I would guess). Then when stuff moves in future it should just be the odd file, and for that hopefully we can use user-defined-redirects on RTD like you suggest. What do you think?

**Comment by lorenabalan** [comment]
Hi @WaylonWalker thanks for looking into this! I've tried `sphinx-reredirects` myself and got similar results to yours. Instead I've updated our readthedocs config with exact redirects and fixed the stable link you've helpfully included in your issue. We have a couple more issues on our backlog to remove the stale links Google has on us and to remove the numbering from our markdown page titles - that way hopefully we'll only have a very small set of redirects we would ever have to do (& maintain for ~60 days).

In the meantime I'm gonna close this issue as resolved, thank you very much for your contribution.
